"""add_users_table

Revision ID: 406187fdc69b
Revises: b5d2ed561d5f
Create Date: 2026-04-13 20:54:22.252738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '406187fdc69b'
down_revision: Union[str, Sequence[str], None] = 'b5d2ed561d5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    from sqlalchemy import inspect as sa_inspect
    inspector = sa_inspect(bind)
    existing_tables = inspector.get_table_names()

    if 'users' not in existing_tables:
        op.create_table('users',
            sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
            sa.Column('userid', sa.String(length=20), nullable=False),
            sa.Column('password_hash', sa.String(length=255), nullable=False),
            sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_users_userid'), 'users', ['userid'], unique=True)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_userid'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
