"""add_nickname_to_users

Revision ID: 4f20a03cba06
Revises: add_kakao_id
Create Date: 2026-04-27 21:42:10.458235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f20a03cba06'
down_revision: Union[str, Sequence[str], None] = 'add_kakao_id'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submissions_external_problem_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_user_id_source'), table_name='submissions')
    op.add_column('users', sa.Column('nickname', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'nickname')
    op.create_index(op.f('ix_submissions_user_id_source'), 'submissions', ['user_id', 'source'], unique=False)
    op.create_index(op.f('ix_submissions_external_problem_id'), 'submissions', ['external_problem_id'], unique=False)
    # ### end Alembic commands ###
