"""add_choices_to_quiz_questions

Revision ID: b185050dd51e
Revises: 115f670aa1ce
Create Date: 2026-05-04 22:58:24.499097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b185050dd51e'
down_revision: Union[str, Sequence[str], None] = '115f670aa1ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_questions', sa.Column('choices', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz_questions', 'choices')
    # ### end Alembic commands ###
