"""add_language_to_hint_categories

Revision ID: dce6ba8425ae
Revises: b185050dd51e
Create Date: 2026-05-11 20:42:50.232672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dce6ba8425ae'
down_revision: Union[str, Sequence[str], None] = 'b185050dd51e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hint_categories', sa.Column('language', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hint_categories', 'language')
    # ### end Alembic commands ###
